apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "symfony-app.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "symfony-app.tlsSecret" . }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "symfony-app.name" . }}
            port:
              number: 80
