{{- if .Values.scheduler.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel-app.name" . }}-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- if .Values.image.pullSecret }}
          imagePullSecrets:
          - name: {{ .Values.image.pullSecret }}
          {{- end }}
          containers:
          - name: scheduler
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["php", "artisan", "schedule:run"]
            {{- if .Values.envFrom }}
            envFrom:
            {{- if .Values.envFrom.configMapName }}
            - configMapRef:
                name: {{ .Values.envFrom.configMapName }}
            {{- end }}
            {{- if .Values.envFrom.secretName }}
            - secretRef:
                name: {{ .Values.envFrom.secretName }}
            {{- end }}
            {{- end }}
            {{- if .Values.env }}
            env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            resources:
              {{- toYaml .Values.scheduler.resources | nindent 14 }}
            {{- if .Values.volumes }}
            volumeMounts:
            {{- range .Values.volumes }}
            {{- $name := .name }}
            {{- range .mounts }}
            - name: {{ $name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if .Values.volumes }}
          volumes:
          {{- range .Values.volumes }}
          - name: {{ .name }}
            persistentVolumeClaim:
              claimName: {{ .claimName }}
          {{- end }}
          {{- end }}
{{- end }}
