{{- if and .Values.envFrom .Values.envFrom.secretName }}
{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.envFrom.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "laravel-app.name" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  PLACEHOLDER: "changeme"
{{- end }}
{{- end }}